In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.0.3'

In [3]:
#Read the data
df = pd.read_csv('laptops.csv')
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [4]:
#How many records are in the dataset?
len(df)

2160

In [19]:
# Strip any leading/trailing spaces and make all columns to lowercase
df.columns = df.columns.str.strip().str.lower()
df

laptop       status   brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           model                cpu  ram  storage storage type       gpu  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      screen touch  final price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [25]:
#How many laptop brands are presented in the dataset?
unique_brands = df['brand'].nunique()
unique_brands

27

In [35]:
#How many columns in the dataset have missing values?
missing_values_per_column = df.isnull().sum()

# Filter the columns that have missing values
columns_with_missing_values = missing_values_per_column[missing_values_per_column > 0]

# Count the number of columns that have missing values
num_columns_with_missing_values = len(columns_with_missing_values)
num_columns_with_missing_values

3

In [44]:
#What's the maximum final price of Dell notebooks in the dataset?
dell_brand = (df[df['brand'] == 'Dell'])
maximum_price = dell_brand['final price'].max()
maximum_price

3936.0

In [ ]:
Find the median value of Screen column in the dataset.
Next, calculate the most frequent value of the same Screen column.
Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step.
Now, calculate the median value of Screen once again.

In [46]:
med = df['screen'].median()
med

15.6

In [49]:
highest = df['screen'].max()
highest

18.0

In [51]:
df['screen'].fillna(highest, inplace = True)

In [53]:
med = df['screen'].median()
med

15.6

#Sum of weights

Select all the "Innjoo" laptops from the dataset.

Select only columns RAM, Storage, Screen.

Get the underlying NumPy array. Let's call it X.

Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

Compute the inverse of XTX.

Create an array y with values [1100, 1300, 800, 900, 1000, 1100].

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

What's the sum of all the elements of the result?

YES

In [55]:
# Filter the DataFrame for 'Innjoo' laptops
innjoo_laptops = df[df['brand'] == 'Innjoo']

# Select only the columns 'RAM', 'Storage', and 'Screen'
innjoo_laptops_ = innjoo_laptops[['ram', 'storage', 'screen']]

# Get the underlying NumPy array
X = innjoo_laptops_.to_numpy()

# Print the NumPy array
print(X)

[[  8.  256.   15.6]
 [  8.  512.   15.6]
 [  4.   64.   14.1]
 [  6.   64.   14.1]
 [  6.  128.   14.1]
 [  6.  128.   14.1]]


In [59]:
# Compute XTX
XTX = np.dot(X.T, X)

# Compute the inverse of XTX
XTX_inverse = np.linalg.inv(XTX)

# Create the array y
y = np.array([1100, 1300, 800, 900, 1000, 1100])

# Compute the result of XTX_inv * X.T * y
XTX_inv_X_T = np.dot(XTX_inverse, X.T)
w = np.dot(XTX_inv_X_T, y)

# Compute the sum of all elements in w
result_sum = np.sum(w)
result_sum

91.29988062995815